### ISSUE TITLE
我有个问题

### ISSUE THREAD

**Issue by buzai** [suconghou/videoproxy#1]
u2b视频播放投屏到tv上面，一旦手机使用ss一类的服务它就无法搜索到电视。这种你有解决方案么

**Comment by suconghou** [comment]
@buzai  投屏使用的dlna协议需要是在一个局域网内,通过udp多播和http协议交互, 如果你的应用程序走代理了,这两个路径就不通了,就没法发现和交互了.

参考 https://github.com/suconghou/u2flutter
